fileserver:
    image: quay.io/tamu_cpt/staticfileserver:latest
    environment:
        ROOT_DIR: /data
        PATH_PREFIX: ${URL_PREFIX}
        AUTOINDEX: ${AUTO_INDEX}
    labels:
        io.rancher.container.pull_image: always
        io.rancher.scheduler.affinity:host_label_soft: role=webserver
    volumes:
        - ${VOLUME_NAME}:/data
    volume_driver: convoy-nfs
