version: '2'
volumes:
    data_volume:
        driver: rancher-nfs
services:
    fileserver:
        image: quay.io/tamu_cpt/staticfileserver:latest
        environment:
            ROOT_DIR: /data
            PATH_PREFIX: ${URL_PREFIX}
            AUTOINDEX: ${AUTO_INDEX}
        labels:
            io.rancher.container.pull_image: always
            io.rancher.scheduler.affinity:host_label_soft: role=webserver
        volumes:
            - data_volume:/data
