.catalog:
  name: CPT Static File Server
  description: Simple place to dump files / folders of stuff that should be provided as downloads for end users.
  version: 1.0.0-rancher1.3
  questions:
  - variable: "URL_PREFIX"
    type: "string"
    label: "Frontend URL Path"
    description: "Subdirectory to serve static files from"
    default: "/dot"
    required: true
  - variable: "AUTO_INDEX"
    type: "string"
    label: "Autoindex"
    description: "Enables auto-indexes for directories if set to 1"
    default: "0"
    required: true

fileserver:
  scale: 1
