.catalog:
  name: CPT Frontend Proxy
  version: 3.0.0-rancher1.3
  description: Proxy service proxying all our backend infrastructure
lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
  load_balancer_config:
    haproxy_config:
      defaults: |-
        stats enable
        stats hide-version
        stats scope .
        stats realm Haproxy\ Statistics
        stats uri /haproxy?stats
