version: '2'
volumes:
    chado_db:
        driver: rancher-nfs
    primary_db:
        driver: rancher-nfs
    apollo_data:
        driver: rancher-nfs
    dbbackup:
        driver: rancher-nfs
    chadobackup:
        driver: rancher-nfs
services:
    # Public access
    remoteuser:
        image: "quay.io/erasche/gx-cookie-proxy:latest"
        environment:
          GALAXY_DB_URL: ${GALAXY_DB_URI}
          GALAXY_SECRET: ${GALAXY_SECRET}
          GXC_BACKEND_URL: "target:8080"
          GXC_LOGLEVEL: DEBUG
        links:
          - apollo:target
        labels:
          io.rancher.container.pull_image: always
    # Galaxy / Private Access
    apiurlremap:
        image: "quay.io/tamu_cpt/urlremap:latest"
        environment:
            INCOMING_PATH_PREFIX: /${CONTEXT_PATH}_api
            OUTGOING_PATH_PREFIX: /${CONTEXT_PATH}
            BACKEND_PORT: 8080
        links:
            - apollo:backend
        labels:
          io.rancher.scheduler.affinity:host_label: role=webserver
    # Data mounted on webserver. This is mostly specific to our deployment. We
    # need the apollo data directory available (i.e. the rancher-nfs volume
    # mounted) on the host(s) running the apollo tools so that they can copy
    # data directories in and out.
    datadir:
        image: "busybox"
        volumes:
            - apollo_data:/opt/apollo/data/
        labels:
          io.rancher.scheduler.affinity:host_label: role=webserver
          io.rancher.container.start_once: true

    apollo:
        image: "quay.io/gmod/apollo:2.5.0"
        environment:
            CONTEXT_PATH: ${CONTEXT_PATH}
            APOLLO_PATH: ${CONTEXT_PATH}
            # Apollo DB Config
            WEBAPOLLO_DB_HOST: db
            WEBAPOLLO_DB_NAME: postgres
            WEBAPOLLO_DB_USERNAME: postgres
            WEBAPOLLO_DB_PASSWORD: postgres
            # Chado DB Config
            CHADO_DB_HOST: chado
            CHADO_DB_NAME: postgres
            CHADO_DB_USERNAME: postgres
            CHADO_DB_PASSWORD: postgres
            # Apollo and Chado DB driver and dialect now set in apollo-config.groovy 
            # to "org.postgresql.Driver" and "org.hibernate.dialect.PostgresPlusDialect" 
            # if you need other options, please use a different image.
            # General Apollo Config
            WEBAPOLLO_COMMON_DATA: /opt/apollo/data/galaxy
            WEBAPOLLO_TRANSLATION_TABLE: '11'
            WEBAPOLLO_USE_CHADO: 'true'
            WEBAPOLLO_REMOTE_USER_AUTH: 'true'
        volumes:
            - apollo_data:/opt/apollo/data/
        links:
            - db:db
            - chado:chado
        ports:
            - 8999:8080/tcp
        labels:
            io.rancher.container.pull_image: always
            io.rancher.scheduler.affinity:host_label: role=compute

    db:
        image: erasche/chado:1.31-jenkins97-pg9.5
        volumes:
          - primary_db:/var/lib/postgresql/data/
        environment:
          INSTALL_CHADO_SCHEMA: 0
          POSTGRES_PASSWORD: postgres
        labels:
          io.rancher.container.pull_image: always
          io.rancher.sidekicks: dbbackup
          io.rancher.scheduler.affinity:host_label: role=compute
    dbbackup:
        image: quay.io/tamu_cpt/postgres-backup:latest
        environment:
          MAX_BACKUPS: 5
          PGHOST: db
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
        links:
          - db
        volumes:
          - dbbackup:/backup
        labels:
          io.rancher.container.pull_image: always
          io.rancher.scheduler.affinity:host_label: role=compute

    chado:
        image: erasche/chado:1.31-jenkins97-pg9.5
        volumes:
          - chado_db:/var/lib/postgresql/data/
        environment:
          INSTALL_CHADO_SCHEMA: 1
          POSTGRES_PASSWORD: postgres
        labels:
          io.rancher.container.pull_image: always
          io.rancher.sidekicks: chadobackup
          io.rancher.scheduler.affinity:host_label: role=compute
    chadobackup:
        image: quay.io/tamu_cpt/postgres-backup:latest
        environment:
          MAX_BACKUPS: 5
          PGHOST: chado
          PGPORT: 5432
          PGUSER: postgres
          PGPASSWORD: postgres
        links:
          - chado
        volumes:
          - chadobackup:/backup
        labels:
          io.rancher.container.pull_image: always
          io.rancher.scheduler.affinity:host_label: role=compute
