barcode:
  image: "quay.io/tamu_cpt/barcode_server:latest"
  ports:
    - 80
  environment:
    BARCODE_LISTEN_PREFIX: "${LISTEN_PATH}"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
lb:
  image: rancher/load-balancer-service
  ports:
  - 80
  labels:
    io.rancher.loadbalancer.target.barcode: 9998=80
  links:
  - barcode:barcode
