.catalog:
  name: CPT Frontend Proxy
  version: 8-rancher2
  description: |
    Proxy service proxying all our backend infrastructure
lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
