version: '2'
volumes:
    chado_db:
        driver: rancher-nfs
    primary_db:
        driver: rancher-nfs
    apollo_data:
        driver: rancher-nfs
    db_backup:
        driver: rancher-nfs
    chado_backup:
        driver: rancher-nfs
services:
    remote_user:
        image: quay.io/erasche/gx-cookie-proxy:v0.9.3
        environment:
          GALAXY_DB_URL: db.postgres.rancher.internal
          GALAXY_SECRET: ${GALAXY_SECRET}
          GXC_BACKEND_URL: target:8080
        links:
          - apollo:target
        ports:
          - "8998:5000"

    apollo:
        image: quay.io/erasche/apollo:cpt
        links:
          - db
          - chado
        ports:
          - "8999:8080"
        environment:
          CONTEXT_PATH: ${CONTEXT_PATH}
          WEBAPOLLO_DB_USERNAME: postgres
          WEBAPOLLO_DB_PASSWORD: postgres
          WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
          WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
          WEBAPOLLO_DB_URI: "jdbc:postgresql://db.apollo.rancher.internal/postgres"
          WEBAPOLLO_CHADO_DB_USERNAME: postgres
          WEBAPOLLO_CHADO_DB_PASSWORD: postgres
          WEBAPOLLO_CHADO_DB_DRIVER: "org.postgresql.Driver"
          WEBAPOLLO_CHADO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
          WEBAPOLLO_CHADO_DB_URI: "jdbc:postgresql://chado.apollo.rancher.internal/postgres"
        volumes:
            - apollo_data:/opt/apollo/data/
        labels:
            io.rancher.container.pull_image: always

    db:
        image: erasche/chado:1.31-jenkins97-pg9.5
        volumes:
            - primary_db:/var/lib/postgresql/data/
        environment:
            INSTALL_CHADO_SCHEMA: 0
            POSTGRES_PASSWORD: postgres
        labels:
            io.rancher.container.pull_image: always
            io.rancher.sidekicks: db_backup
    db_backup:
        image: quay.io/tamu_cpt/postgres-backup:latest
        environment:
            MAX_BACKUPS: 5
            PGHOST: db
            PGPORT: 5432
            PGUSER: postgres
            PGPASSWORD: postgres
        links:
            - db
        volumes:
            - db_backup:/backup
        labels:
            io.rancher.container.pull_image: always

    chado:
        image: erasche/chado:1.31-jenkins97-pg9.5
        volumes:
            - chado_db:/var/lib/postgresql/data/
        environment:
            INSTALL_CHADO_SCHEMA: 1
            POSTGRES_PASSWORD: postgres
        labels:
            io.rancher.container.pull_image: always
            io.rancher.sidekicks: db_backup
    chado_backup:
        image: quay.io/tamu_cpt/postgres-backup:latest
        environment:
            MAX_BACKUPS: 5
            PGHOST: db
            PGPORT: 5432
            PGUSER: postgres
            PGPASSWORD: postgres
        links:
            - db
        volumes:
            - chado_backup:/backup
        labels:
            io.rancher.container.pull_image: always
