.catalog:
  name: GUANINE
  version: 1-rancher1.3
  description: |
     Galaxy stUdent AssessmeNt INfrastructurE
  questions:
  - variable: "BACKEND_HOST"
    type: "string"
    label: "Backend Host + Protocol Path"
    description: ""
    default: "https://cpt.tamu.edu/"
    required: true
  - variable: "BACKEND_URL_PREFIX"
    type: "string"
    label: "Backend URL Path"
    description: "Subdirectory to run GUANINE API server under. Must not have trailing or leading slashc."
    default: "guanine-backend"
    required: true
  - variable: "FRONTEND_URL_PREFIX"
    type: "string"
    label: "Frontend URL Path"
    description: "Subdirectory to serve JS frontend from. Must have leading slash."
    default: "/guanine"
    required: true
