.catalog:
  name: CPT Apollo
  version: 2.0.5-rancher1.3.8
  description: |
    Genome annotation editor with a Java Server backend and a Javascript client
    that runs in a web browser as a JBrowse plugin.
  questions:
  - variable: "CONTEXT_PATH"
    type: "string"
    description: "Subdirectory/ctx path to access the file at. DO NOT INCLUDE LEADING OR TRAILING SLASH. Internal slashes are fine."
    label: "Context Path"
    default: "apollo"
    required: true
  - variable: "GALAXY_SECRET"
    type: "string"
    description: "Secret to access galaxy DB"
    label: "Galaxy Secret"
    default: "THE DEFAULT IS NOT SECURE!"
    required: true
  - variable: "GALAXY_DB_URI"
    type: "string"
    description: "Database URI"
    label: "Galaxy Database URI"
    default: "postgresql://postgres:postgres@db.postgres.rancher.internal:5432/postgres?client_encoding=utf8&sslmode=disable"
    required: true
  - variable: "GXC_GRAPHITE_SERVER"
    type: "string"
    description: "Usually the influxdb instance from the Prometheus instance associated with this rancher deployment."
    label: "Graphite Server"
    default: "influxdb.Prometheus.rancher.internal"
    required: true
  - variable: "GXC_GRAPHITE_PREFIX"
    type: "string"
    description: "Graphite Prefix"
    label: "Graphite Prefix"
    default: "system.edu.tamu.cpt.apollo"
    required: true
