lb:
  image: rancher/load-balancer-service
  ports:
    - 127.0.0.1:9999:9999
  external_links:
    - barcode/lb:lb
    - jenkins-ci/jenkins-primary:jenkins-primary
    - cacao/api-server:cacao-api
    - cacao/static-server:cacao-static
    - guanine/api-server:guanine-api
    - guanine/static-server:guanine-static
    - phagereg/registry:phagereg
    - ontoapi/static-server:ontoapi
    - spanindb/spanindb-api:spanindb-api
    - spanindb/static-server:spanindb-static
    - library/library:library
    - downloads/fileserver:downloads
    - apollo/apollo:apollo
  labels:
    # http://docs.rancher.com/rancher/v1.2/en/cattle/adding-load-balancers/#syntax-of-the-combination-of-all-optional-fields
    io.rancher.scheduler.affinity:host_label: role=webserver
    io.rancher.loadbalancer.target.barcode/lb: /barcodes=5000
    io.rancher.loadbalancer.target.jenkins-ci/jenkins-primary: /jenkins2=8080
    io.rancher.loadbalancer.target.cacao/api-server: /cacao-backend=8000
    io.rancher.loadbalancer.target.cacao/static-server: /cacao=80
    io.rancher.loadbalancer.target.guanine/api-server: /guanine-backend=8000
    io.rancher.loadbalancer.target.guanine/static-server: /guanine=80
    io.rancher.loadbalancer.target.phagereg/registry: /phage-registry=8094
    io.rancher.loadbalancer.target.ontoapi/static-server: /onto_api=80
    io.rancher.loadbalancer.target.spanindb/spanindb-api: /spanindb-api=8000
    io.rancher.loadbalancer.target.spanindb/static-server: /spanindb=80
    io.rancher.loadbalancer.target.library/library: /library=80
    io.rancher.loadbalancer.target.downloads/fileserver: /dot=80
    io.rancher.loadbalancer.target.apollo/apollo: /apollo-dev=8080
  tty: true
  stdin_open: true
