spanindb-api:
    image: quay.io/tamu_cpt/spanindb:latest
    environment:
        DJANGO_URL_PREFIX: ${BACKEND_URL_PREFIX}/
        CORS_ORIGINS: cpt.tamu.edu,localhost
        ALLOWED_HOSTS: cpt.tamu.edu,localhost

static-server:
    image: quay.io/tamu_cpt/staticfileserver:latest
    volumes_from:
      - static-builder
    environment:
      ROOT_DIR: /output
      PATH_PREFIX: ${FRONTEND_URL_PREFIX}
    labels:
        io.rancher.sidekicks: static-builder

static-builder:
    image: quay.io/tamu_cpt/spanindb-frontend:latest
    volumes:
        - /output
    labels:
        io.rancher.container.start_once: true
