version: '2'
volumes:
    data:
        driver: rancher-nfs
services:
    wordpress:
        image: wordpress
        links:
            - mysql
        ports:
            - 80
        environment:
            WORDPRESS_DB_PASSWORD: ${DATABASE_PASSWORD}

    mysql:
        image: tutum/mysql:latest
        volumes:
            - data:/var/lib/mysql
        environment:
            MYSQL_PASS: ${DATABASE_PASSWORD}
        mem_limit: 4000000000
