version: '2'
.catalog:
  name: CPT Frontend Proxy
  version: 4.5.0-rancher1.3
  description: Proxy service proxying all our backend infrastructure
services:
  lb:
    scale: 1
    start_on_create: true
    lb_config:
      certs: []
      port_rules:
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: apollo/apiurlremap         , path: /apollo_api     , target_port: 80}
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: apollo/remoteuser          , path: /apollo         , target_port: 5000}
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: barcode/lb                 , path: /barcodes       , target_port: 5000 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: cacao/remoteuser           , path: /cacao-backend  , target_port: 5000 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: cacao/static-server        , path: /cacao          , target_port: 80 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: downloads-depot/fileserver , path: /cargoport      , target_port: 80 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: downloads/fileserver       , path: /dot            , target_port: 80 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: guanine/api-server         , path: /guanine-backend, target_port: 8000 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: guanine/static-server      , path: /guanine        , target_port: 80 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: jenkins-ci/jenkins-primary , path: /jenkins2       , target_port: 8080 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: library/library            , path: /library        , target_port: 80 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: lims/api-server            , path: /lims-backend   , target_port: 8000 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: lims/static-server         , path: /lims           , target_port: 80 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: phagereg/registry          , path: /phage-registry , target_port: 8094 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: spanindb/spanindb-api      , path: /spanindb-api   , target_port: 8000 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: spanindb/static-server     , path: /spanindb       , target_port: 80 }
      - {hostname: '', priority: 1, protocol: http, source_port: 9999, service: grafana/grafana            , path: /grafana        , target_port: 3000 }
      #- {hostname: '', priority: 1, protocol: http, source_port: 9999, service: ontoapi/static-server      , path: /onto_api       , target_port: 80 }
    health_check:
      response_timeout: 2000
      healthy_threshold: 2
      port: 42
      unhealthy_threshold: 3
      interval: 2000





lb:
  scale: 1
  load_balancer_config:
    haproxy_config: {}
  health_check:
    port: 42
    interval: 2000
    unhealthy_threshold: 3
    healthy_threshold: 2
    response_timeout: 2000
  load_balancer_config:
    haproxy_config:
      defaults: |-
        stats enable
        stats hide-version
        stats scope .
        stats realm Haproxy\ Statistics
        stats uri /haproxy?stats
