library:
  image: "grimy55/i-librarian"
  ports:
    - 80
  labels:
    io.rancher.sidekicks: library-datavolume
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  volumes:
    - /etc/localtime:/etc/localtime:ro
  volumes_from:
    - library-datavolume

library-datavolume:
  image: "busybox"
  volumes:
    - ${volume_work}:/library
  labels:
    io.rancher.container.start_once: true
  volume_driver: convoy-nfs
  entrypoint: ["chown", "-R", "1000:1000", "/library"]
