.catalog:
  name: CPT Library
  description: |
    Statefull Web based PDF Library
  version: 1-rancher0
barcode:
  scale: 1
  health_check:
    port: 80
    interval: 10000
    initializing_timeout: 2000
    unhealthy_threshold: 3
    strategy: recreate
    request_line: GET "/" "HTTP/1.0"
    healthy_threshold: 2
    response_timeout: 2000
