apollo:
    image: quay.io/erasche/apollo:cpt
    links:
        - db
        - chado
    ports:
        - 8080
    environment:
      WEBAPOLLO_DB_USERNAME: postgres
      WEBAPOLLO_DB_PASSWORD: password
      WEBAPOLLO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_DB_URI: "jdbc:postgresql://db/postgres"
      WEBAPOLLO_CHADO_DB_USERNAME: postgres
      WEBAPOLLO_CHADO_DB_PASSWORD: password
      WEBAPOLLO_CHADO_DB_DRIVER: "org.postgresql.Driver"
      WEBAPOLLO_CHADO_DB_DIALECT: "org.hibernate.dialect.PostgresPlusDialect"
      WEBAPOLLO_CHADO_DB_URI: "jdbc:postgresql://chado/postgres"
    volume_driver: convoy-nfs
    volumes:
        - ${volume_apollo}:/data
db:
    image: postgres:9.5
    volume_driver: convoy-nfs
    volumes:
        - ${volume_db}:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: postgres
chado:
    image: erasche/chado:latest
    volume_driver: convoy-nfs
    volumes:
        - ${volume_chado}:/var/lib/postgresql/data
    environment:
        INSTALL_CHADO_SCHEMA: 1
        POSTGRES_PASSWORD: postgres
