barcode:
  image: "quay.io/tamu_cpt/barcode_server:latest"
  ports:
    - 80
  environment:
    BARCODE_LISTEN_PREFIX: "${LISTEN_PATH}"
  labels:
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
lb:
  image: rancher/load-balancer-service
  ports:
  - "${LISTEN_PORT}:80"
  labels:
    io.rancher.loadbalancer.target.barcode: 80=80
    io.rancher.scheduler.affinity:host_label: role=webserver
  links:
  - barcode:barcode
