.catalog:
  name: CACAO
  version: 2-rancher4
  description: |
    CACAO Service
  questions:
  - variable: "BACKEND_HOST"
    type: "string"
    label: "Backend Host + Protocol Path"
    description: ""
    default: "https://cpt.tamu.edu/"
    required: true
  - variable: "BACKEND_URL_PREFIX"
    type: "string"
    label: "Backend URL Path"
    description: "Subdirectory to run CACAO API server under. Must not have trailing or leading slashc."
    default: "cacao-backend"
    required: true
  - variable: "FRONTEND_URL_PREFIX"
    type: "string"
    label: "Frontend URL Path"
    description: "Subdirectory to serve JS frontend from. Must have leading slash."
    default: "/cacao"
    required: true
  - variable: "volume_cacao_db"
    type: "string"
    description: "Work volume to save jenkins data"
    label: "Convoy Volume Name"
    default: "cacao-db"
    required: true
